import { Alert, Button, Chip, CircularProgress, Container, Dialog, DialogActions, DialogContent, Divider, Paper, Rating, Stack, TextField, Typography } from "@mui/material";
import { useEffect, useState } from "react";
import axios from "axios";
import { aprovarFeedback, aprovarSolicitacao, listarAvaliacoesMentoriaAdmin, listarFeedbacksAdmin, listarSolicitacoes, loginAdmin, logoutAdmin, recusarFeedback, recusarSolicitacao, sessaoAdmin, type AvaliacaoMentoriaAdmin, type FeedbackAdmin, type SolicitacaoMentor } from "../../services/Auth/controllers/admin";
import { fonts } from "../../styles/theme";

const mensagemErro = (erro: unknown, padrao: string) =>
  axios.isAxiosError<{ detail?: string }>(erro) ? erro.response?.data?.detail || padrao : padrao;

export default function Admin() {
  const [autenticado, setAutenticado] = useState(false), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false);
  const [email, setEmail] = useState(""), [senha, setSenha] = useState(""), [erro, setErro] = useState("");
  const [solicitacoes, setSolicitacoes] = useState<SolicitacaoMentor[]>([]), [feedbacks, setFeedbacks] = useState<FeedbackAdmin[]>([]);
  const [avaliacoes, setAvaliacoes] = useState<AvaliacaoMentoriaAdmin[]>([]), [recusa, setRecusa] = useState<SolicitacaoMentor | null>(null), [motivo, setMotivo] = useState("");

  const carregar = async () => { const [s, f, a] = await Promise.all([listarSolicitacoes(), listarFeedbacksAdmin(), listarAvaliacoesMentoriaAdmin()]); setSolicitacoes(s); setFeedbacks(f); setAvaliacoes(a); };
  useEffect(() => { sessaoAdmin().then(() => { setAutenticado(true); return carregar(); }).catch(() => {}).finally(() => setLoading(false)); }, []);
  const entrar = async (e: React.FormEvent) => { e.preventDefault(); setBusy(true); setErro(""); try { await loginAdmin(email, senha); setAutenticado(true); await carregar(); } catch (err: unknown) { setErro(mensagemErro(err, "Não foi possível entrar.")); } finally { setBusy(false); } };
  const aprovar = async (id: number) => { setBusy(true); setErro(""); try { await aprovarSolicitacao(id); await carregar(); } catch (err: unknown) { setErro(mensagemErro(err, "Não foi possível aprovar.")); } finally { setBusy(false); } };
  const confirmarRecusa = async () => { if (!recusa) return; setBusy(true); try { await recusarSolicitacao(recusa.id, motivo); setRecusa(null); setMotivo(""); await carregar(); } finally { setBusy(false); } };
  const analisarFeedback = async (id: number, acao: "aprovar" | "recusar") => { setBusy(true); setErro(""); try { await (acao === "aprovar" ? aprovarFeedback(id) : recusarFeedback(id)); await carregar(); } catch (err: unknown) { setErro(mensagemErro(err, "Não foi possível analisar o feedback.")); } finally { setBusy(false); } };

  if (loading) return <Stack alignItems="center" p={8}><CircularProgress /></Stack>;
  if (!autenticado) return <Container maxWidth="xs" sx={{ py: 10 }}><Stack component="form" onSubmit={entrar} gap={2} sx={{ p: 4, bgcolor: "secondary.main", borderRadius: 4 }}><Typography variant="h4" fontFamily={fonts.hero} fontWeight={700}>Administração</Typography>{erro && <Alert severity="error">{erro}</Alert>}<TextField label="E-mail administrativo" type="email" value={email} onChange={e => setEmail(e.target.value)} /><TextField label="Senha" type="password" value={senha} onChange={e => setSenha(e.target.value)} /><Button type="submit" variant="contained" disabled={busy}>Entrar</Button></Stack></Container>;

  return <Stack sx={{ minHeight: "100vh", bgcolor: "secondary.light" }}><Container maxWidth="lg" sx={{ py: 5 }}>
    <Stack direction="row" justifyContent="space-between"><Typography variant="h3" fontFamily={fonts.hero} fontWeight={700}>Painel administrativo</Typography><Button onClick={async () => { await logoutAdmin(); setAutenticado(false); }}>Sair</Button></Stack>{erro && <Alert severity="error" sx={{ my: 2 }}>{erro}</Alert>}
    <Typography variant="h5" sx={{ mt: 3, mb: 2 }}>Solicitações de novos mentores</Typography><Stack gap={2}>{!solicitacoes.length && <Alert severity="info">Nenhuma solicitação recebida.</Alert>}{solicitacoes.map(x => <Paper key={x.id} sx={{ p: 3, borderRadius: 3 }}><Stack direction={{ xs: "column", md: "row" }} justifyContent="space-between" gap={2}><Stack><Typography variant="h6">{x.nome}</Typography><Typography>{x.email} • {x.especialidade}</Typography><Typography sx={{ mt: 1 }}>{x.biografia}</Typography><Typography variant="caption">Status: {x.status}</Typography></Stack>{x.status === "pendente" && <Stack direction="row" gap={1} alignItems="center"><Button variant="contained" disabled={busy} onClick={() => void aprovar(x.id)}>Aprovar</Button><Button color="error" variant="outlined" disabled={busy} onClick={() => setRecusa(x)}>Recusar</Button></Stack>}</Stack></Paper>)}</Stack>
    <Divider sx={{ my: 5 }} /><Typography variant="h5" sx={{ mb: 1 }}>Feedbacks da plataforma</Typography><Typography color="text.secondary" sx={{ mb: 3 }}>Apenas comentários autorizados podem ser publicados na página inicial.</Typography><Stack gap={2}>{!feedbacks.length && <Alert severity="info">Nenhum feedback recebido.</Alert>}{feedbacks.map(x => <Paper key={x.id} sx={{ p: 3, borderRadius: 3 }}><Stack direction={{ xs: "column", md: "row" }} justifyContent="space-between" gap={2}><Stack gap={.75}><Stack direction="row" gap={1} alignItems="center" flexWrap="wrap"><Typography variant="h6">{x.autor_nome}</Typography><Chip size="small" label={x.autor_papel} /><Chip size="small" color={x.status === "aprovado" ? "success" : x.status === "recusado" ? "error" : "warning"} label={x.status} /></Stack><Rating value={x.nota} readOnly size="small" /><Typography>{x.comentario}</Typography><Typography variant="caption">{x.autoriza_publicacao ? "Autorizou publicação" : "Não autorizou publicação"}</Typography></Stack>{x.status === "pendente" && <Stack direction="row" gap={1}><Button variant="contained" disabled={busy || !x.autoriza_publicacao} onClick={() => void analisarFeedback(x.id, "aprovar")}>Publicar</Button><Button color="error" variant="outlined" disabled={busy} onClick={() => void analisarFeedback(x.id, "recusar")}>Recusar</Button></Stack>}</Stack></Paper>)}</Stack>
    <Divider sx={{ my: 5 }} /><Typography variant="h5" sx={{ mb: 1 }}>Avaliações de trilhas e mentores</Typography><Typography color="text.secondary" sx={{ mb: 3 }}>Visão geral da qualidade das experiências de mentoria.</Typography><Stack gap={2}>{!avaliacoes.length && <Alert severity="info">Nenhuma avaliação de mentoria recebida.</Alert>}{avaliacoes.map(x => <Paper key={x.id} sx={{ p: 3, borderRadius: 3 }}><Typography variant="h6">{x.trilha_titulo}</Typography><Typography variant="body2">Mentor: {x.mentor_nome} • Empreendedor: {x.empreendedor_nome}</Typography><Stack direction={{ xs: "column", sm: "row" }} gap={2} sx={{ my: 1 }}><Stack direction="row" gap={1}><Typography>Trilha:</Typography><Rating size="small" readOnly value={x.nota_trilha} /></Stack><Stack direction="row" gap={1}><Typography>Mentor:</Typography><Rating size="small" readOnly value={x.nota_mentor} /></Stack></Stack>{x.comentario && <Typography>{x.comentario}</Typography>}</Paper>)}</Stack>
  </Container><Dialog open={!!recusa} onClose={() => setRecusa(null)} fullWidth maxWidth="sm"><DialogContent><Typography variant="h6">Recusar solicitação</Typography><TextField fullWidth multiline minRows={3} sx={{ mt: 2 }} label="Motivo (opcional)" value={motivo} onChange={e => setMotivo(e.target.value)} /></DialogContent><DialogActions><Button onClick={() => setRecusa(null)}>Cancelar</Button><Button color="error" variant="contained" disabled={busy} onClick={() => void confirmarRecusa()}>Confirmar recusa</Button></DialogActions></Dialog></Stack>;
}
